# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'RotenTomatoClient' do
pod 'AFNetworking', '2.2.1'
pod 'MBProgressHUD', '~> 0.9.1'

end

target 'RotenTomatoClientTests' do

end

